    -
      name:  Disable Nic
      win_psexec:
        command: '{{ item }}'
        executable: C:\temp\PsExec.exe
        elevated: yes
        nobanner: yes
        system: yes
        interactive: yes
      with_items:
        - powershell.exe netsh interface set interface Ethernet0 disable
      async: 45
      poll: 0
