    -
      name:  Exclude Windows
      win_psexec:
        command: '{{ item }}'
        executable: C:\temp\PsExec.exe
        elevated: yes
        nobanner: yes
        system: yes
        interactive: yes
      with_items:
        - powershell.exe Add-MpPreference -ExclusionPath "C:\temp"
        - powershell.exe Add-MpPreference -ExclusionPath "C:\Windows"
        - powershell.exe Add-MpPreference -ExclusionExtension ".exe"
        - powershell.exe Add-MpPreference -ExclusionExtension ".bat"