    - name:  Run Malware Files as System
      win_psexec:
        command: '{{ item }}'
        executable: C:\Windows\System32\PsExec.exe
        elevated: yes
        nobanner: yes
        system: yes
        interactive: yes
        wait: no
      with_items:
        - C:\Windows\System32\untitled1.exe

    - name:  Run Malware Files as System
      win_psexec:
        command: '{{ item }}'
        executable: C:\Windows\System32\PsExec.exe
        elevated: yes
        nobanner: yes
        system: yes
        interactive: yes
        wait: no
      with_items:
        - C:\temp\QuasarPayload.exe
        - C:\temp\Payload.bat