    - name:  Run Malware Files as System
      win_psexec:
        command: '{{ item }}'
        executable: C:\temp\PsExec.exe
        elevated: yes
        nobanner: yes
        system: yes
        interactive: yes
        wait: no
      with_items:
        - C:\temp\pupy.exe
        - C:\temp\launcher.bat
        - C:\temp\QRT.exe