    -
      name:  Powershell scripties
      win_psexec:
        command: '{{ item }}'
        executable: C:\temp\PsExec.exe
        elevated: yes
        nobanner: yes
        interactive: yes
      with_items:
        - powershell.exe Register-ScheduledJob -Name '3Yaik22es' -ScriptBlock { Set-NetFirewallProfile -Profile Domain, Public, Private -Enabled False } -RunNow -RunEvery 00:05:00
        - powershell.exe Register-ScheduledJob -Name '3Ya2ikees' -ScriptBlock { Set-MpPreference -DisableRealtimeMonitoring $true } -RunNow -RunEvery 00:02:00
