    - name: Upload Malware
      win_copy:
        src: 'files/{{item}}'
        dest: 'C:\Windows\System32\{{item}}'
      with_items:
        - "{{empire}}"
        - "{{covenant}}"
        - "{{pupy}}"