-
  name: Check a connection
  hosts: windows-server
  tasks:
    - name: Enable firewall for Domain, Public and Private profiles
      win_firewall:
        state: disabled
        profiles:
        - Domain
        - Private
        - Public
